### ISSUE TITLE
Glass Connected Texture Issue

### ISSUE THREAD

**Issue by Omegampyre** [mullak99/mullak99sFaithful#2]
I have been testing out your pack, and when loading it with MCPatcher and putting the glass blocks in certain configurations (or panes for that matter), the default texture for glass is shown, and the black clear glass texture is not. This issue occurs with normal glass only, and not stained. If you need further information or screenshots to resolve the problem I would be happy to provide.

**Comment by mullak99** [comment]
What configurations? Send me some screenshots, and what version of MInecraft are you using?
